on:
  repository_dispatch:
    types:
      - update-bridge
env:
  AWS_REGION: us-west-2
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GO111MODULE: "on"
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NUGET_PUBLISH_KEY: ${{ secrets.NUGET_PUBLISH_KEY }}
  PROVIDER: aws
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
  PULUMI_API: https://api.pulumi-staging.io
  PULUMI_LOCAL_NUGET: ${{ github.workspace }}/nuget
  PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  TRAVIS_OS_NAME: linux
  BRIDGE_VERSION: ${{ github.event.client_payload.ref }}
jobs:
  update-bridge:
    name: update-bridge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Checkout Scripts Repo
        uses: actions/checkout@v2
        with:
          path: ci-scripts
          repository: pulumi/scripts
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.goversion }}
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.nodeversion}}
          registry-url: https://registry.npmjs.org
      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{matrix.dotnetverson}}
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{matrix.pythonversion}}
      - name: Install Chg for changelog
        run: sudo npm install -g chg
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@d62853bc9e466834c74cefb34fad78535582e21a
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@b811287a6e06bb7e5d8b91132b839c67e3f9c6ed
      - name: Update Bridge version
        run: |
          cd provider && go mod edit -require github.com/pulumi/pulumi-terraform-bridge/v2@${{ env.BRIDGE_VERSION }} && cd ../
          cd provider && go mod tidy && cd ../
      - name: Build tfgen & provider binaries
        run: make build_sdks
      - name: Create changelog entry
        run: |
          chg add "Upgrade to ${{ env.BRIDGE_VERSION }} of pulumi-terraform-bridge"
      - name: git status
        run: git status
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          ref: "update-bridge/${{ env.BRIDGE_VERSION }}-${{ github.run_id }}"
          author_name: pulumi-bot
          author_email: "bot@pulumi.com"
    strategy:
      fail-fast: true
      matrix:
        dotnetversion:
          - 3.1.301
        goversion:
          - 1.15.x
        nodeversion:
          - 13.x
        pythonversion:
          - "3.7"
  pull-request:
    runs-on: ubuntu-latest
    needs: update-bridge
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "update-bridge/${{ env.BRIDGE_VERSION }}-${{ github.run_id }}"
          destination_branch: "master"
          pr_title: "Upgrade to ${{ env.BRIDGE_VERSION }} of pulumi-terraform-bridge"
          pr_body: "*Automated PR*"
          pr_label: "automation/merge"
          pr_allow_empty: true
          github_token: ${{ secrets.PULUMI_BOT_TOKEN }}
